name: AI Competitive Intelligence Monitor

on:
  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'full-monitor'
        type: choice
        options:
          - full-monitor
          - scrape-only
          - analyze-only
          - generate-data-only

env:
  NODE_ENV: production

jobs:
  # Job 1: Run monitoring and generate static data
  monitor-and-generate:
    runs-on: ubuntu-latest
    
    # Grant permissions to write to the repository
    permissions:
      contents: write
      actions: read
      issues: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          cd github-actions-backend
          npm ci
      
      - name: Install Puppeteer browsers
        run: |
          cd github-actions-backend
          npx puppeteer browsers install chrome
      
      - name: Initialize database
        run: |
          cd github-actions-backend
          mkdir -p data
          node scripts/init-db.js
          # Note: add-companies.sh requires running server, skipping in CI
          # The init-db.js already adds 4 initial companies
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          THEBRAIN_API_KEY: ${{ secrets.THEBRAIN_API_KEY }}
          THEBRAIN_BRAIN_ID: ${{ secrets.THEBRAIN_BRAIN_ID }}
      
      - name: Run intelligent scraper
        if: ${{ inputs.action != 'analyze-only' && inputs.action != 'generate-data-only' }}
        run: |
          cd github-actions-backend
          timeout 1800 node scraper-wrapper.js || echo "Scraper completed or timed out"
        timeout-minutes: 30
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          THEBRAIN_API_KEY: ${{ secrets.THEBRAIN_API_KEY }}
          THEBRAIN_BRAIN_ID: ${{ secrets.THEBRAIN_BRAIN_ID }}
          GITHUB_ACTIONS: 'true'
      
      - name: Run AI analysis and TheBrain integration
        if: ${{ inputs.action != 'scrape-only' && inputs.action != 'generate-data-only' }}
        run: |
          cd github-actions-backend
          # Run ultra-enhanced AI analysis with entity extraction and auto-grouping
          node ai-analyzer-ultra-wrapper.js full || echo "Ultra-enhanced AI analysis completed"
          # Sync to TheBrain if credentials are available
          node thebrain-sync-wrapper.js full || echo "TheBrain sync completed or skipped"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          THEBRAIN_API_KEY: ${{ secrets.THEBRAIN_API_KEY }}
          THEBRAIN_BRAIN_ID: ${{ secrets.THEBRAIN_BRAIN_ID }}
          GITHUB_ACTIONS: 'true'
        timeout-minutes: 30
      
      - name: Generate static data files for GitHub Pages
        run: |
          cd github-actions-backend
          node generate-static-data.js
          # Copy generated files to root for GitHub Pages
          cp -r ../api-data/* ../api-data/ || echo "No api-data directory to copy"
          # Ensure api-data directory exists in root
          mkdir -p ../api-data
          # Copy any new files
          cp -f ../api-data/* ../api-data/ 2>/dev/null || echo "Static data generated"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          THEBRAIN_API_KEY: ${{ secrets.THEBRAIN_API_KEY }}
      
      - name: Update status file
        run: |
          cd github-actions-backend
          echo "{
            \"last_run\": \"$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)\",
            \"status\": \"success\",
            \"workflow_run_id\": \"$GITHUB_RUN_ID\",
            \"action\": \"${{ inputs.action || 'scheduled' }}\",
            \"backend\": \"github-actions\"
          }" > ../api-data/workflow-status.json
      
      - name: Commit and push updated data
        run: |
          # Configure git with GitHub Actions bot credentials
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add all changes in api-data directory
          git add api-data/
          
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            # Commit the changes
            git commit -m "🤖 Auto-update monitoring data - $(date -u +%Y-%m-%d\ %H:%M:%S\ UTC)"
            
            # Pull latest changes and rebase our changes on top
            git pull --rebase https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
            
            # Push with explicit token and retry logic
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          fi
      
      - name: Upload database backup
        uses: actions/upload-artifact@v4
        with:
          name: monitor-database-backup
          path: github-actions-backend/data/monitor.db
          retention-days: 30

  # Job 2: Deploy to GitHub Pages (runs after monitor-and-generate)
  deploy:
    needs: monitor-and-generate
    runs-on: ubuntu-latest
    if: success()
    
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout updated code
        uses: actions/checkout@v4
        with:
          ref: main  # Get the latest version with updated data
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Upload the entire repository (includes api-data)
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Job 3: Create alerts for high-priority changes
  create-alerts:
    needs: monitor-and-generate
    runs-on: ubuntu-latest
    if: success()
    
    steps:
      - name: Checkout updated code
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Check for high-priority changes
        id: check-changes
        run: |
          # Check if there are any high-priority changes (relevance score >= 8)
          HIGH_PRIORITY=$(jq '[.changes[] | select(.relevance_score >= 8)] | length' api-data/changes.json 2>/dev/null || echo "0")
          echo "high_priority_count=$HIGH_PRIORITY" >> $GITHUB_OUTPUT
          
          if [ "$HIGH_PRIORITY" -gt 0 ]; then
            echo "Found $HIGH_PRIORITY high-priority changes"
            # Get the details
            jq -r '.changes[] | select(.relevance_score >= 8) | "- \(.company): \(.summary) (Score: \(.relevance_score)/10)"' api-data/changes.json > /tmp/changes.txt || echo "No changes file"
            echo "changes_details<<EOF" >> $GITHUB_OUTPUT
            cat /tmp/changes.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
      
      - name: Create GitHub Issue for high-priority alerts
        if: steps.check-changes.outputs.high_priority_count > 0
        uses: actions/github-script@v7
        with:
          script: |
            const count = ${{ steps.check-changes.outputs.high_priority_count }};
            const changes = `${{ steps.check-changes.outputs.changes_details }}`;
            
            const body = `# 🔴 High Priority Competitive Intelligence Alert
            
            **${count} high-priority changes detected** in competitor monitoring.
            
            ## Changes Detected:
            ${changes}
            
            ## Next Steps:
            - Review the [full dashboard](https://redmorestudio.github.io/ai-competitive-monitor) for detailed analysis
            - Check the [workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for technical details
            - Consider updating our competitive strategy based on these changes
            
            ---
            *This is an automated alert from the AI Competitive Intelligence Monitor.*
            *Generated: ${new Date().toISOString()}*`;
            
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🔴 ${count} High Priority Competitive Intelligence Alert${count > 1 ? 's' : ''}`,
              body: body,
              labels: ['competitive-intel', 'high-priority', 'automated', 'ai-generated']
            });
            
            console.log(`Created issue #${issue.data.number} for high-priority alerts`);
      
      # Step to send email notifications
      - name: Send email notifications
        if: ${{ secrets.SMTP_HOST != '' && secrets.SMTP_USER != '' && secrets.SMTP_PASS != '' }}
        run: |
          cd github-actions-backend
          # Install nodemailer if not already in package.json
          npm install nodemailer
          # Run email notification check
          node email-notifications.js check
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      
      # Daily summary email (only at 9 AM UTC)
      - name: Send daily summary email
        if: ${{ github.event_name == 'schedule' && contains('09:00', github.event.schedule) && secrets.SMTP_HOST != '' }}
        run: |
          cd github-actions-backend
          node email-notifications.js daily
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
